config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pages#home"
  get "about" => "pages#about" #creates about_path
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  respond_to :html

  def index
    @pins = Pin.all
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

 def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "not authorized to edit this pin" if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_headerbar.html.erb
<!this is the navbar at the top of every page, got from bootstrap site, rendered in application.html>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My WEBSITE</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to "Home", root_path %></li>
        
         <% if user_signed_in? %>
         <li><%=link_to "About", about_path %></li>
          <%end%>
        <li class="dropdown">
          </ul>
        </li>
      </ul>

      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%=link_to "Log out", destroy_user_session_path, method: :delete%></li>
        <li><%=link_to "Pins", pins_path %></li>
        
        <%else %>
                <li><%=link_to "Sign In", new_user_session_path%></li>

        <%end%>
        <li><%=link_to "Edit Acct", edit_user_registration_path %></li>
          </ul>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
	<%= render 'layouts/headerbar' %>
	<div class="container">
		<%= yield %>
		<% flash.each do |name,msg| %>
		<%= content_tag(:div,msg, class: "alert alert-info")%>
		<%end%>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>we are working on omr app</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1><font color="white">Welcome!</font></h1>
  <%if user_signed_in? %>
  # do something
  <%else %>

  	<p><font color="white">sign up <%= link_to "Here", new_user_registration_path, class: "btn btn-warning"%> or </font> <%= link_to "Sign In", new_user_session_path, class: "btn btn-info"%>
  	<%end %>
</div>

<p>Find me in app/views/pages/home.html.erb</p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
<style type="text/css">
   body { background: azure  !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :string %><br>
    <%= f.text_field :string, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
    
<% @pins.each do |pin| %>
    <div class="box panel panel-default">
     
        <%= image_tag pin.image.url(:medium) %>
        <div class="panel-body">
            <%= pin.description %>
            <%= pin.string %>
            <%= link_to 'Show', pin %>
            <%if pin.user == current_user %>
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </div>
   </div>
<%end%>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
	<%= image_tag @pin.image.url(:medium) %>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>
<p>
  <strong>String:</strong>
  <%= @pin.string %>
</p>

<% if @pin.user == current_user %>
	<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%end>%>
<%= link_to 'Back', pins_path %>